#.travis.yml

sudo: required
dist: trusty
language: node_js
node_js:
  - "12.11.1"

cache:
  directories:
    - $HOME/.npm
    - node_modules

before_install:
  - npm i -g npm@6.13.6

install:
  - npm i --silent --no-optional

script:
  - npm run test:ci
  - npm run build
